### ISSUE TITLE
Noto Sans Tai Viet: U+2026 HORIZONTAL ELLIPSIS wrong in IE11

### ISSUE THREAD

**Issue by akccakcctw** [googlefonts/noto-fonts#1151]
I use the earlyaccess style from https://fonts.google.com/earlyaccess#Noto+Sans+Tai+Viet

```css
/*
 * Noto Sans Tai Viet (Tai Viet) http://www.google.com/fonts/earlyaccess
 */
@font-face {
  font-family: 'Noto Sans Tai Viet';
  font-style: normal;
  font-weight: 400;
  src: url(//fonts.gstatic.com/ea/notosanstaiviet/v1/NotoSansTaiViet-Regular.eot);
  src: url(//fonts.gstatic.com/ea/notosanstaiviet/v1/NotoSansTaiViet-Regular.eot?#iefix) format('embedded-opentype'),
       url(//fonts.gstatic.com/ea/notosanstaiviet/v1/NotoSansTaiViet-Regular.woff2) format('woff2'),
       url(//fonts.gstatic.com/ea/notosanstaiviet/v1/NotoSansTaiViet-Regular.woff) format('woff'),
       url(//fonts.gstatic.com/ea/notosanstaiviet/v1/NotoSansTaiViet-Regular.ttf) format('truetype');
}

```

and found the ellipsis sign (U+2026) becomes tofu in IE11 (Chrome and Firefox are just fine):
![2018-04-20 12 07 16](https://user-images.githubusercontent.com/16360246/39030486-cb2ae9d0-4494-11e8-9aa7-7220eafb61fc.png)

It can be reproduce easily:
```css
.ellipsis {
  width: 150px;
  text-overflow: ellipsis;
  font-family: "Noto Sans Tai Viet", sans-serif;
  overflow: hidden;
  white-space: nowrap;
}
```

Also, the ellipsis sign is correct in other font ( `Noto Sans TC`, for example) in IE11.
